#! /usr/bin/perl
use warnings;
use utf8;

print "enter radius: ";
chomp( my $radius = <STDIN> );

my $pi = 3.141592654;

my $circumference = 2 * $pi * ( $radius > 0 ? $radius : 0 );

print "Radius $radius => circumference $circumference\n";
