#! /usr/bin/perl

use 5.014;

while( <> ) {
  chomp;
  if( /(?<word>\w*a)\b(?<next>.{0,5})/ ) {
    say "Matched : |$`<$&>$'| 'word' contains '$+{word}', follwed by '$+{next}'";
  }
  else {
    say "No match: |$_|";
  }
}
