#! /usr/bin/perl -w
use 5.014;
use List::Util qw( max );
use Scalar::Util qw( looks_like_number );

# identify, normalise and sort numbers
my @nums = sort { $a <=> $b } map { 1 * $_ } grep { looks_like_number $_ } @ARGV;

# find max width
my $w = max map { length } @ARGV;

# print
say sprintf "%${w}s", $_ foreach @nums;
