#! /usr/bin/perl -w
use 5.014;
use List::Util qw( sum );

my @fred = above_average( 1..10 );
say "\@fred is @fred";
say "(Should be 6 7 8 9 10)";
my @barney = above_average( 100, 1..10 );
say "\@barney is @barney";
say "(Should be just 100)";


sub mean {
  return sum( @_ ) / @_;
}

sub above_average {
  my $mean = mean( @_ );
  return map { $_ >= $mean ? ( $_ ) : () } @_;
}
