#! /usr/bin/perl
use 5.014;

my $range = 100;

my $secret = int( 1 + rand $range );

while ( <> ) {
  chomp;

  if ( m/^(quit|exit)?$/i ) {
    say "quitter!";
    last;
  }
  elsif ( m/\D/ ) {
    say "u wot m8?";
  }
  elsif ( $_ < $secret ) {
    say "too low";
  }
  elsif ( $_ > $secret ) {
    say "too high";
  }
  elsif ( $_ == $secret ) {
    say "bang on!";
    last;
  }
}
